version: '3.4'

services:
    producer:
        build: ./bgpStream/
        network_mode: "host"
        volumes: 
            - ./zombieHunter.sh:/app/zombieHunter.sh
            - ./config.ini:/app/config.ini
            - ./data/logs:/app/logs/
        env_file:
            - env
        environment: 
            - JOB=producer
        entrypoint:
            - /bin/bash
            - /app/zombieHunter.sh
        
    analyzer:
        build: ./bgpConfluent/
        network_mode: "host"
        volumes: 
            - ./zombieHunter.sh:/app/zombieHunter.sh
            - ./config.ini:/app/config.ini
            - ./data/logs:/app/logs/
        env_file:
            - env
        environment: 
            - JOB=analyzer
        entrypoint:
            - /bin/bash
            - /app/zombieHunter.sh 

    scheduler:
        build: ./bgpConfluent
        network_mode: "host"
        volumes:
            - ./zombieHunter.sh:/app/zombieHunter.sh 
            - ./config.ini:/app/config.ini
            - ./data/logs:/app/logs/
        env_file:
            - env
        environment: 
            - JOB=scheduler
        entrypoint:
            - /bin/bash
            - /app/zombieHunter.sh

    detector:
        build: ./bgpConfluent
        network_mode: "host"
        volumes: 
            - ./zombieHunter.sh:/app/zombieHunter.sh
            - ./config.ini:/app/config.ini
            - ./data/logs:/app/logs/
            - ./data/zombies:/app/zombies/
        env_file:
            - env
        environment: 
            - JOB=detector
        entrypoint:
            - /bin/bash
            - /app/zombieHunter.sh
